"use client";

import { useState, useEffect, Suspense } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { Download, Printer, FileText, ChevronRight } from "lucide-react";
import { satellites, riskGradient, type SatelliteTrack } from "@/utils/mosip-data";

/* ── Report Generator ──────────────────────────────────────────────────────── */
function generateReport(sat: SatelliteTrack): string {
  const date = new Date().toISOString().split("T")[0];
  const time = new Date().toUTCString();
  const riskLabel = sat.risk >= 75 ? "CRITICAL THREAT — IMMEDIATE ACTION REQUIRED" : sat.risk >= 55 ? "ELEVATED CONGESTION — MONITORING REQUIRED" : "NOMINAL OPERATION — STANDARD MONITORING";
  const complianceText = sat.risk >= 75
    ? "NON-COMPLIANT. Post-mission disposal plan not certified for passive atmospheric decay within IADC-mandated 25-year window. Projected deorbit lifetime exceeds 40 years without active intervention. Active debris removal strongly recommended."
    : sat.risk >= 55
    ? "CONDITIONALLY COMPLIANT. Meets baseline ESA/IADC standards but exhibits marginal deorbit timeline metrics. Revised disposal plan incorporating augmented drag devices or controlled deorbit burn recommended."
    : "FULLY COMPLIANT. Meets all applicable ESA Guideline 4.2, NASA-STD-8719.14B, and IADC Space Debris Mitigation Guidelines. Passivation of residual propellant systems mandatory at decommissioning.";

  const recommendations = sat.risk >= 75
    ? `   [PRIORITY 1 — CRITICAL]:\n      Initiate collision avoidance delta-V thrust burn of 0.45 m/s within 48h.\n\n   [PRIORITY 2 — HIGH]:\n      Coordinate Space Traffic Management ephemeris update with national authority.\n\n   [PRIORITY 3 — HIGH]:\n      Schedule Active Debris Removal (ADR) assessment for end-of-life phase.\n\n   [PRIORITY 4 — MEDIUM]:\n      Conduct fuel passivation audit. Vent all hypergolic pressurant tanks.`
    : sat.risk >= 55
    ? `   [PRIORITY 1 — MEDIUM]:\n      File updated orbital ephemeris with STM coordination office.\n\n   [PRIORITY 2 — MEDIUM]:\n      Review and certify deorbit timeline compliance against IADC 25-year rule.\n\n   [PRIORITY 3 — LOW]:\n      Conduct passivation readiness review at T-6 months before EoL.`
    : `   [PRIORITY 1 — ROUTINE]:\n      Maintain conjunction screening at 72-hour cadence.\n\n   [PRIORITY 2 — ROUTINE]:\n      Confirm passivation procedures documented in decommission plan.\n\n   [PRIORITY 3 — INFORMATIONAL]:\n      Submit annual sustainability report per ITU filing requirements.`;

  return `╔══════════════════════════════════════════════════════════════════════════╗
║         MOSIP ORBITAL INTELLIGENCE OFFICE — CLASSIFIED BRIEF            ║
║              Multi-Agent Orbital Sustainability Platform v2.1            ║
╚══════════════════════════════════════════════════════════════════════════╝

REGISTRY ID   : MOSIP-${sat.id}-${sat.orbit}-ALPHA
GENERATION    : ${date}  |  ${time}
CLASSIFICATION: RESTRICTED — INTERNAL USE ONLY
GENERATED BY  : MOSIP LangGraph 8-Agent Assessment Pipeline

══════════════════════════════════════════════════════════════════════════

SECTION 1 — SUBJECT IDENTIFICATION
──────────────────────────────────────────────────────────────────────────
  TARGET NAME        : ${sat.name}
  NORAD CATALOG ID   : ${sat.id}
  OPERATIONAL REGIME : ${sat.orbit}
  MEAN ALTITUDE      : ${sat.alt} km
  ORBITAL VELOCITY   : ${sat.velocity}
  OPERATING ENTITY   : ${sat.operator}
  MISSION STATUS     : Active — Telemetry Link Established

══════════════════════════════════════════════════════════════════════════

SECTION 2 — COLLISION RISK ASSESSMENT
──────────────────────────────────────────────────────────────────────────
  AGGREGATE RISK INDEX  : ${sat.risk}%
  RISK CLASSIFICATION   : ${riskLabel}

  RISK FACTOR BREAKDOWN:
  ┌─────────────────────────────────┬──────────┐
  │ Factor                          │ Score    │
  ├─────────────────────────────────┼──────────┤
  │ Debris Shell Occupancy          │ ${String(Math.round(sat.risk * 0.45)).padEnd(8)} │
  │ Conjunction Probability         │ ${String(Math.round(sat.risk * 0.30)).padEnd(8)} │
  │ Altitude Regime Density         │ ${String(Math.round(sat.risk * 0.15)).padEnd(8)} │
  │ Cross-Sectional Area Exposure   │ ${String(Math.round(sat.risk * 0.10)).padEnd(8)} │
  └─────────────────────────────────┴──────────┘

══════════════════════════════════════════════════════════════════════════

SECTION 3 — COMPLIANCE ASSESSMENT  [ESA / IADC / NASA RAG AUDIT]
──────────────────────────────────────────────────────────────────────────
  COMPLIANCE GRADE  : ${sat.compliance}
  REGULATORY STATUS : ${sat.risk >= 75 ? "NON-COMPLIANT" : sat.risk >= 55 ? "CONDITIONALLY COMPLIANT" : "FULLY COMPLIANT"}

  ASSESSMENT NARRATIVE:
  ${complianceText}

  REGULATORY FRAMEWORKS EVALUATED:
  • IADC-02-01 Rev.4 — Space Debris Mitigation Guidelines
  • ESA-ADMIN-IPOL(2014)2 — Space Debris Mitigation Policy
  • NASA-STD-8719.14B — Process for Limiting Orbital Debris
  • UN A/RES/62/217 — Space Debris Mitigation Guidelines
  • ITU Radio Regulations — Coordination and Notification Procedures

══════════════════════════════════════════════════════════════════════════

SECTION 4 — SUSTAINABILITY & ENVIRONMENTAL IMPACT
──────────────────────────────────────────────────────────────────────────
  SUSTAINABILITY INDEX   : ${sat.sustainability}/100
  FORECAST CLASSIFICATION: ${sat.forecast.toUpperCase()}

  LONG-TERM RISK PROPAGATION:
  ┌─────────────────────┬──────────────────────────────────────────┐
  │ Projection Horizon  │ Estimated Aggregate Collision Risk        │
  ├─────────────────────┼──────────────────────────────────────────┤
  │ Current (Baseline)  │ ${String(sat.risk + "%").padEnd(42)} │
  │ 5-Year Projection   │ ${String(Math.min(100, Math.round(sat.risk * 1.12)) + "%").padEnd(42)} │
  │ 10-Year Projection  │ ${String(Math.min(100, Math.round(sat.risk * 1.30)) + "%").padEnd(42)} │
  │ 25-Year Projection  │ ${String(Math.min(100, Math.round(sat.risk * 1.62)) + "%").padEnd(42)} │
  └─────────────────────┴──────────────────────────────────────────┘

══════════════════════════════════════════════════════════════════════════

SECTION 5 — DIRECTIVE ACTIONS & RECOMMENDATIONS
──────────────────────────────────────────────────────────────────────────
${recommendations}

══════════════════════════════════════════════════════════════════════════

SECTION 6 — AGENT PIPELINE CERTIFICATION
──────────────────────────────────────────────────────────────────────────
  This report was synthesized by the following verified MOSIP agents:

  [✓] Supervisor Agent     — Task decomposition and graph routing
  [✓] Orbital Agent        — Regime, apogee, perigee, velocity analysis
  [✓] Collision Agent      — Debris density and conjunction scoring
  [✓] Compliance Agent     — ESA/IADC/NASA regulatory audit (RAG)
  [✓] Sustainability Agent — Orbital burden and footprint modeling
  [✓] Forecast Agent       — 5/10/25-year trajectory propagation
  [✓] Mitigation Agent     — Action synthesis and priority ordering
  [✓] Documentation Agent  — Executive brief compilation

══════════════════════════════════════════════════════════════════════════
  REPORT END — MOSIP ORBITAL INTELLIGENCE OFFICE
  © 2026 MOSIP Platform. For authorized personnel only.
══════════════════════════════════════════════════════════════════════════`;
}

/* ── Main ──────────────────────────────────────────────────────────────────── */
function ReportCenterContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const idParam = searchParams.get("id");

  const [selectedId, setSelectedId] = useState(idParam || String(satellites[0].id));
  const [reportText, setReportText] = useState("");

  useEffect(() => {
    const sat = satellites.find((s) => s.id.toString() === selectedId) || satellites[0];
    setReportText(generateReport(sat));
  }, [selectedId]);

  useEffect(() => {
    if (idParam) setSelectedId(idParam);
  }, [idParam]);

  const selectedSat = satellites.find((s) => s.id.toString() === selectedId) || satellites[0];

  const handlePrint = () => {
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(`<html><head><title>MOSIP Report – ${selectedSat.name}</title>
      <style>body{background:#02040a;color:#94a3b8;font-family:'Courier New',monospace;font-size:11px;padding:32px;white-space:pre-wrap;line-height:1.7}</style>
      </head><body>${reportText}</body></html>`);
    w.document.close();
    w.print();
  };

  const handleDownload = () => {
    const blob = new Blob([reportText], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `MOSIP-${selectedSat.id}-${selectedSat.orbit}-report.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  return (
    <div className="flex h-[calc(100vh-var(--topbar-h))] overflow-hidden cyber-grid">
      {/* ── Left Sidebar — Satellite Selector ─────────────────────────────── */}
      <div className="w-[260px] shrink-0 border-r border-white/[0.04] flex flex-col" style={{ background: "rgba(2,4,10,0.7)" }}>
        <div className="border-b border-white/[0.05] p-4">
          <span className="eyebrow block mb-1">Select Target</span>
          <h2 className="text-sm font-semibold uppercase tracking-wider text-white">Report Target</h2>
        </div>
        <div className="flex-1 overflow-y-auto p-2">
          {satellites.map((sat) => {
            const isSelected = sat.id.toString() === selectedId;
            const riskColor = sat.risk >= 75 ? "#ff3366" : sat.risk >= 55 ? "#ffb700" : "#00ff9d";
            return (
              <button
                key={sat.id}
                onClick={() => { setSelectedId(String(sat.id)); router.push(`/reports?id=${sat.id}`); }}
                className={`w-full flex items-center gap-2.5 rounded-lg px-3 py-2.5 text-left transition-all mb-0.5 border-l-2 ${
                  isSelected
                    ? "bg-[rgba(0,212,255,0.06)] border-[#00d4ff]"
                    : "border-transparent hover:bg-white/[0.02] hover:border-white/10"
                }`}
              >
                <div className="flex-1 min-w-0">
                  <span className="block truncate text-xs font-semibold text-white">{sat.name}</span>
                  <span className="font-digital text-[9px] text-slate-500">{sat.id} · {sat.orbit}</span>
                </div>
                <div className="shrink-0 text-right">
                  <span className="font-digital text-xs font-bold" style={{ color: riskColor }}>{sat.risk}%</span>
                </div>
                {isSelected && <ChevronRight size={10} className="text-[#00d4ff]/50 shrink-0" />}
              </button>
            );
          })}
        </div>
      </div>

      {/* ── Right — Report Panel ──────────────────────────────────────────── */}
      <div className="flex flex-1 flex-col overflow-hidden">
        {/* Toolbar */}
        <div
          className="flex items-center justify-between border-b border-white/[0.04] px-6 py-3"
          style={{ background: "rgba(2,4,10,0.88)", backdropFilter: "blur(12px)" }}
        >
          <div className="flex items-center gap-3">
            <FileText size={14} className="text-[#00d4ff]/60" />
            <div>
              <span className="eyebrow block">Classified Brief</span>
              <span className="text-xs font-semibold text-white">{selectedSat.name}</span>
            </div>
            <span
              className="font-digital text-[8px] uppercase px-2 py-0.5 rounded border"
              style={{
                borderColor: selectedSat.risk >= 75 ? "rgba(255,51,102,0.3)" : selectedSat.risk >= 55 ? "rgba(255,183,0,0.3)" : "rgba(0,212,255,0.2)",
                color: selectedSat.risk >= 75 ? "#ff3366" : selectedSat.risk >= 55 ? "#ffb700" : "#00d4ff",
              }}
            >
              {selectedSat.compliance} · {selectedSat.risk}%
            </span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleDownload}
              className="btn-ghost flex items-center gap-1.5 rounded-lg px-4 py-2 font-digital text-[10px] uppercase tracking-wider"
            >
              <Download size={12} />
              Download .txt
            </button>
            <button
              onClick={handlePrint}
              className="btn-ghost flex items-center gap-1.5 rounded-lg px-4 py-2 font-digital text-[10px] uppercase tracking-wider"
            >
              <Printer size={12} />
              Print / PDF
            </button>
          </div>
        </div>

        {/* Document */}
        <motion.div
          key={selectedId}
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className="flex-1 overflow-y-auto p-6"
        >
          <div
            className="relative rounded-xl border border-white/[0.04] overflow-hidden"
            style={{ background: "#030308", minHeight: "600px" }}
          >
            {/* RESTRICTED watermark */}
            <div
              className="pointer-events-none absolute inset-0 flex items-center justify-center select-none"
              style={{ zIndex: 0 }}
            >
              <span
                className="font-digital text-7xl font-bold text-white/[0.022] uppercase tracking-[0.5em]"
                style={{ transform: "rotate(-35deg)", userSelect: "none" }}
              >
                RESTRICTED
              </span>
            </div>

            {/* Report content */}
            <pre
              className="relative z-10 p-6 font-digital text-[10.5px] text-slate-300 leading-[1.75] whitespace-pre-wrap select-text"
              style={{ fontFamily: "'JetBrains Mono', 'Courier New', monospace" }}
            >
              {reportText}
            </pre>
          </div>
        </motion.div>
      </div>
    </div>
  );
}

export default function ReportsPage() {
  return (
    <Suspense fallback={
      <div className="grid h-full min-h-screen place-items-center font-digital text-xs uppercase tracking-[0.3em] text-[#00d4ff]/40">
        Loading report engine...
      </div>
    }>
      <ReportCenterContent />
    </Suspense>
  );
}
